In [1]:
import numpy as np

In [2]:
zeros=np.zeros((10,))
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
vowels = np.array(list('aeiou'))
print (vowels)

['a' 'e' 'i' 'o' 'u']


In [4]:
ones =np.ones ((2,5),dtype=int)
print(ones )

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [5]:
myarray1  =np.array([[2.7,  -2,  -19],[0,  3.4,  99.9],[10.6,  0,  13]])
print (myarray1)

[[  2.7  -2.  -19. ]
 [  0.    3.4  99.9]
 [ 10.6   0.   13. ]]


In [6]:
myarray2 = np.arange(4,61,4,float).reshape(3,5)
print(myarray2)

[[ 4.  8. 12. 16. 20.]
 [24. 28. 32. 36. 40.]
 [44. 48. 52. 56. 60.]]


In [7]:
np.shape(ones) 

(2, 5)

In [8]:
print(myarray2.dtype)

float64


In [9]:
np.size(myarray1)

9

In [10]:
print(ones.ndim)

2


In [11]:
vowels[[1,2]]

array(['e', 'i'], dtype='<U1')

In [12]:
myarray1[[1,2]]

array([[ 0. ,  3.4, 99.9],
       [10.6,  0. , 13. ]])

In [13]:
myarray1[ :0]

array([], shape=(0, 3), dtype=float64)

In [14]:
myarray1[[0]]

array([[  2.7,  -2. , -19. ]])

In [15]:
myarray1 [: : -1]

array([[ 10.6,   0. ,  13. ],
       [  0. ,   3.4,  99.9],
       [  2.7,  -2. , -19. ]])

In [16]:
divisor=3
out=np.divide(ones,divisor)
print(out)

[[0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]]


In [17]:
myarray2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(3, 3)

print(myarray2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
myarray1+myarray2

array([[  3.7,   0. , -16. ],
       [  4. ,   8.4, 105.9],
       [ 17.6,   8. ,  22. ]])

In [19]:
newarray=myarray1-myarray2
print(newarray)

[[  1.7  -4.  -22. ]
 [ -4.   -1.6  93.9]
 [  3.6  -8.    4. ]]


In [20]:
myarray1*myarray2

array([[  2.7,  -4. , -57. ],
       [  0. ,  17. , 599.4],
       [ 74.2,   0. , 117. ]])

In [21]:
myarray3=myarray1@myarray2
print(myarray3)

[[-138.3 -156.6 -174.9]
 [ 712.9  816.2  919.5]
 [ 101.6  125.2  148.8]]


In [22]:
myarray1/myarray2

array([[ 2.7       , -1.        , -6.33333333],
       [ 0.        ,  0.68      , 16.65      ],
       [ 1.51428571,  0.        ,  1.44444444]])

In [23]:
myarray1**3/2

array([[ 9.841500e+00, -4.000000e+00, -3.429500e+03],
       [ 0.000000e+00,  1.965200e+01,  4.985015e+05],
       [ 5.955080e+02,  0.000000e+00,  1.098500e+03]])

In [24]:
np.around(myarray2**(1/2)/2,2)

array([[0.5 , 0.71, 0.87],
       [1.  , 1.12, 1.22],
       [1.32, 1.41, 1.5 ]])

In [25]:
ones.transpose()
myarray2.transpose

<function ndarray.transpose>

In [26]:
(np.sort(vowels))[: : -1]

array(['u', 'o', 'i', 'e', 'a'], dtype='<U1')

In [27]:
myarray1.sort(axis=0)

In [28]:
myarray2A,myarray2B,myarray2C,myarray2D,myarray2E=np.array_split(myarray2,5,axis=1)
print(myarray2A,myarray2B,myarray2C,myarray2D,myarray2E)

[[1]
 [4]
 [7]] [[2]
 [5]
 [8]] [[3]
 [6]
 [9]] [] []


In [29]:
(np.array([myarray2A,myarray2B,myarray2C])).reshape(3,3)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [30]:
myarray4=np.arange(-1,9.5,0.25)
a1,a2,a3=np.array_split(myarray4,3,axis=0)

In [31]:
myarray4.sum()

173.25

In [32]:
myarray4.sum(axis=0)

173.25

In [33]:
myarray4.max()

9.25

In [34]:
myarray4.min()

-1.0

In [35]:
myarray4.std(axis=0)

3.0302296392627848

In [37]:
myarray4.mean(axis=0)

4.125