In [11]:
import numpy as np

In [12]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)
print(arr.shape)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)


In [15]:
array=np.zeros((3,3))
print(array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
array=np.ones((3,3))
print(array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,10])
print(np.reshape(a, (2, 5)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [20]:
a = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(a)
print('flattening a...')
print(a.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
flattening a...
[1 2 3 4 5 6 7 8 9]


In [22]:
a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
b=np.array([[11,12,13],[14,15,16],[17,18,19]])
np.hstack((a,b))

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [23]:
a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
b=np.array([[11,12,13],[14,15,16],[17,18,19]])
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [25]:
arr = np.array([1, 2, 3, 4,5,6,7,8,9,10])

print(arr[1])
print(arr[1:5])

2
[2 3 4 5]


In [30]:
a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(a)
print (np.min(a))
print (np.max(a))
print (np.mean(a))
print (np.median(a))
print (np.std(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
9
5.0
5.0
2.581988897471611
