In [2]:
import numpy.matlib  

In [3]:
import numpy as np

In [4]:
a=np.array([[1,2],[3,4]])
b=np.array([[11,12],[13,14]])
np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [6]:
m=np.array([[1,2],[3,4]])
print(m)
w,v=np.linalg.eig(m)
print("eigen values:",w)

[[1 2]
 [3 4]]
eigen values: [-0.37228132  5.37228132]


In [7]:
a=np.array([[3,1],[1,2]])
b=np.array([9,8])
x=np.linalg.solve(a,b)
print(x)

[2. 3.]


In [8]:
m=np.matrix([[1,6,0],[5,8,6],[1,0,9]])
print(np.linalg.inv(m))

[[-0.44444444  0.33333333 -0.22222222]
 [ 0.24074074 -0.05555556  0.03703704]
 [ 0.04938272 -0.03703704  0.13580247]]


In [9]:
rank=np.linalg.matrix.rank(m)
print("rank of the matrix is:",rank)

AttributeError: module 'numpy.linalg' has no attribute 'matrix'